# -*- coding: utf-8 -*-
"""email_spam.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ihPDf2l1fWYEhShFNBBsibjEHjz_0ms0
"""

import pandas as pd
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
import joblib

dataset=pd.read_csv('emails.csv', on_bad_lines='skip')
subject=dataset['text']
label=dataset['spam']

x_train,x_test,y_train,y_test=train_test_split(subject,label,test_size=0.75,shuffle=True,stratify=label)

vectorizer=TfidfVectorizer()
x_train_vec=vectorizer.fit_transform(x_train)
x_test_vec=vectorizer.transform(x_test)

model=GaussianNB()
model.fit(x_train_vec.toarray(),y_train)

y_pred=model.predict(x_test_vec.toarray())

print(accuracy_score(y_test,y_pred))

vectorizer.fit(x_train)
joblib.dump(model,"spam_model.pkl")
joblib.dump(vectorizer,"vectorizer.pkl")  



